name: Jekyll site CI/CD

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      env:
        DOCKER_HUB: ${{ secrets.DOCKER_HUB }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
      run: |
        ls -l
        echo 'Docker login'
        docker login -u $DOCKER_HUB -p $DOCKER_HUB_KEY
        echo 'Running build...'
        docker build . -t aimvector/staticpgdeploy:ui-content-latest
        echo'Pushing...'
        docker push aimvector/staticpgdeploy:ui-content-latest
        echo 'Done!'
#       run: |
#         docker run \
#         -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
#         jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
